[project]
name = "analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "librosa>=1.0.0",
    "numpy>=2.5.2",
    "python-multipart>=0.0.32",
    "soundfile>=0.14.0",
    "uvicorn>=0.52.4",
]
